var mongoose = require("./CollabCRUD/node_modules/mongoose");
var User = require("./CollabCRUD/models/user.js");
var Project = require("./CollabCRUD/models/project.js");
var loremIpsum = require("lorem-ipsum");

var connection = "mongodb://localhost:27017";

mongoose.connect(connection);

var names = ["Rickie Lair",
    "Morgan Vanhouten",
    "Dacia Kepner",
    "Particia Garvin",
    "Rueben Lindner",
    "Maddie Lewicki",
    "Tarsha Kells",
    "Jake Delao",
    "Noemi Grate",
    "Amalia Appleberry",
    "Coletta Goodnight",
    "Belen Sherrow",
    "Julissa Mcnear",
    "Roberto Shock",
    "Geneva Runyan",
    "Hermine Wedeking",
    "Ellamae Beckman",
    "Tracee Hey",
    "Loni Kemper",
    "Diana Whidbee",
    "Johna Nicoletti",
    "Cherly Richerson",
    "Shae Whitis",
    "Angelina Mcintyre",
    "Georgine Coffee",
    "Melynda Sypher",
    "Salley Gano",
    "Maurita Spada",
    "Tresa Bahena",
    "Rosita Nino",
    "Lemuel Sweigart",
    "Lucretia Damelio",
    "Apryl Gosha",
    "Carlotta Edgemon",
    "Albertha Oommen",
    "Nisha Bashore",
    "Sammie Nystrom",
    "Marlana Burket",
    "Lester Orem",
    "Stacy Maloof",
    "Homer Edling",
    "Lottie Kissell",
    "Sudie Mcgough",
    "Donnetta Troupe",
    "Marlyn Gover",
    "Delmer Danz",
    "Adelaide Fox",
    "Virgil Neumann",
    "Lettie Struthers",
    "Shayna Shreve"
];

var usernames = [
    "napkintorpid",
    "barbequedgreaseproof",
    "dioxiderawchicken",
    "xenonsamovar",
    "trimsyrup",
    "wombledpulse",
    "gabbrofunnel",
    "pluckedshirt",
    "turduckendislike",
    "corvusforked",
    "pentagonadara",
    "timelyphenol",
    "texttechnician",
    "chalkurban",
    "pancakesfingers",
    "cultivatedagreeable",
    "shoddyplague",
    "fussyporcupine",
    "wiredeciles",
    "nibblesdiss",
    "goalstruggling",
    "huskyresidual",
    "dashboardbowen",
    "endtropical",
    "amniotelightyear",
    "nutarena",
    "starvelingno",
    "trapmousse",
    "meitneriumkenyan",
    "hugcatalytic",
    "minanimal",
    "restlessrelax",
    "slipscake",
    "bulgarianvertigo",
    "ergotregions",
    "fernsteak",
    "prologtile",
    "acceleratortaught",
    "harasslanky",
    "flowercustom",
    "achesswoosh",
    "masculineentropy",
    "talussoulful",
    "coconutlament",
    "earlobecrispy",
    "professdalton",
    "inferiorflammable",
    "amniotepure",
    "shabbyunfolded",
    "digitmalicious"
];

var projects = [
    "FitVide",
    "howtherinb",
    "microme",
    "funch",
    "jquirror",
    "retroke",
    "modplax",
    "sageDB.js",
    "Minimals",
    "jDatable",
    "lionato",
    "jakedpaper",
    "envil.io",
    "intWeek",
    "Kizzle",
    "iFramer",
    "jq.carty",
    "Ghostr.js",
    "iphonefile",
    "Sounder",
    "Charp",
    "requireman",
    "Arctive.js",
    "nipport",
    "reforms",
    "jPagic",
    "tomason",
    "biter.js",
    "clint",
    "nsecurid",
    "fluid.net",
    "nsecury",
    "Sharter",
    "memberreds",
    "syntables",
    "hijscape",
    "googleanel",
    "metremacs",
    "Mactor",
    "Uglifico",
    "datajama",
    "Anywhen",
    "Crowsereo",
    "Sandrials",
    "wikit",
    "incalthjs",
    "edget",
    "dillian",
    "juicks",
    "rialider",
    "scieti",
    "routs",
    "sider",
    "Avisandar",
    "Squirrowse",
    "rabba",
    "cools",
    "railr",
    "Miningage",
    "lrthom",
    "crowservm",
    "inver",
    "yprotat",
    "Kicketbug",
    "fletic",
    "dicture",
    "farier",
    "jskatables",
    "Imagen",
    "Residesh",
    "spiniTip",
    "nimarked",
    "spectToolt",
    "tracules",
    "jqPager",
    "sigmailway",
    "Hovery",
    "monicoder",
    "inputer.js",
    "gride",
    "seques",
    "icallow",
    "jgronetic",
    "prics.js",
    "mover",
    "mon.comber",
    "Sliderning",
    "firmie",
    "gmapt",
    "fundle.RSS",
    "mochoice",
    "Html5sling",
    "Dandle",
    "frample",
    "scrollery",
    "liveal",
    "Mail.it",
    "140media",
    "Coding.js",
    "axelCools",
    "webar",
    "ranslanet",
    "Backboney",
    "Threesass",
    "Squarkly",
    "jsshteint",
    "phone.js",
    "eidor",
    "jsviewport",
    "hestem",
    "jsdify",
    "zip2addy",
    "Ext.layer",
    "newfobjs",
    "jelley",
    "valize",
    "player.js",
    "exagaka",
    "jtabs",
    "cartside",
    "swinkingjs",
    "ugliff",
    "Jsonv.js",
    "opency",
    "tiddle",
    "asyntation",
    "sugart",
    "DaumEdita",
    "lyonry",
    "mcms3",
    "svgboard",
    "mobilerian",
    "backy",
    "motive.git",
    "Crude.com",
    "throme",
    "flate",
    "JSLiveine",
    "quild",
    "contln",
    "websole",
    "Minuke",
    "futube",
    "noops",
    "mechr",
    "Inderno",
    "TicToe",
    "githundle",
    "hamcaro",
    "Panet",
    "profxmppjs",
    "pars.js",
    "fario",
    "Numbnail",
    "hubarium",
    "Extreat",
    "narries",
    "jq.card",
    "writor",
    "workedpape",
    "jQswig",
    "jPlate",
    "Acebox2D",
    "Jsonv.js",
    "Awwate",
    "fstringer",
    "Eurefilter",
    "stion7",
    "twickem",
    "echoneGBA",
    "spacedire",
    "qwraphilog",
    "com.js",
    "Chingo",
    "real.org",
    "ipad.js",
    "revelytic",
    "basell",
    "bone.page",
    "yetic",
    "TiShare",
    "tweetbugs",
    "Vanage",
    "kinon",
    "flard",
    "LiipView",
    "nodeit",
    "gistors",
    "Skells",
    "popupporth",
    "chromess",
    "KnobKnock",
    "html5tuton",
    "mark2",
    "finana",
    "gmail.js",
    "Tagiler",
    "micatePick",
    "konatoes",
    "Andrive"
];

// var times = 0;
// (function next() {
//     setTimeout(function() {
//         gen();
//         times++;
//         if (times < 200) {
//             next();
//         }
//     }, 100);
// })()

usernames.forEach(function(username) {
    var nameIndex = Math.floor(Math.random() * names.length),
        name = names[nameIndex],
        nproj = Math.floor((Math.random() * 6) + 1);

    if (nproj > projects.length)
        nproj = projects.length;

    names.splice(nameIndex, 1);

    var user = new User({
        username: username,
        name: name
    });
    user.projects = [];

    for (var i = 0; i < nproj; i++) {
        var projIndex = Math.floor(Math.random() * projects.length);

        var proj = new Project({
            author: username,
            name: projects[projIndex],
            description: loremIpsum(),
            reputation: Math.floor(Math.random() * 50)
        });
        user.projects.push(proj._id);
        projects.splice(projIndex, 1);

        proj.save(function(err, p) {

        });
    }

    user.save(function(err, user) {
        console.log("User " + user.name + " saved.");
    });
});
